services:
  investment-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment-generator
    env_file: .env
    ports:
      - 8000:8000   
    volumes:
        # Create a named volume for persistent data storage with read and write permissions
        - reports-data:/app/reports:rw

volumes:
  reports-data:
    name: investment-report-generator-data
